### ISSUE TITLE
How do I build?

### ISSUE THREAD

**Issue by rickyvetter** [camlspotter/ocamloscope.2#29]
Hi there!

I'm trying to get this project to build and I'm running into a little bit of trouble.

Running `omake` by itself complains about a missing `OMakeroot` and `OMyMakefile` on the first two runs, which I copied over from https://github.com/camlspotter/ocamloscope to satisfy. After running with those two files I run `omake` a third time and get an error like the following:

```
*** omake error:
   File server/OMakefile: line 66, characters 5-17
   unbound variable: global.WithMerlin
```

I see that `withMerlin` is defined in the ngrok folder, but I don't understand how to tie everything together here.

I'd love to be able to build this project locally. Do you know where I might have gone wrong or what I'm missing to get everything working on my end?

PS - I was stalking for solutions and on Twitter I saw some complaints with 0.10.x omake, so I ran this with both 0.10.2 and 0.9.8.6-0.rc1 with the same results.

**Comment by camlspotter** [comment]
Thanks for trying.

I am sorry but I have to say that ocamlscope.2 is not yet ready to build out of the box:  it depends on lots of developing versions of my libraries which are not opam-ready.

Please give me some time to fix ocamloscope.2 opam-installable.

**Comment by camlspotter** [comment]
Btw, you can install softwares with `omake.0.10.x`.  

Unfortunately it has introduced several bugs in its persistent build mode (i.e. `omake -P`).  If you want to develop things with `omake` by yourself, use `omake.0.9.8.6-0.rc1`.

**Comment by rickyvetter** [comment]
Thanks for the information! Very excited about this project :) If there's anything you could use help with in the mean time, let me know.

**Comment by camlspotter** [comment]
I made branch `b2.0.0` which should compile with `opam pin add ocamloscope .`  I hope it will help you.

**Comment by rickyvetter** [comment]
Worked like a charm! Thanks for setting that up.
